name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: stylua
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: stylua-github --all-files

      - name: codespell
        if: success() || failure()
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: codespell --all-files
